{
 "title": "Isilon Data Insights Cluster Detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({job=\"isilon\"}, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome to the Isilon Detail Dashboard for $cluster",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* Use the pull down at the very top left of the page (next to the spiral icon) to select which dashboard you want to look at.\n* Use the cluster and other pull downs to select the cluster and protocol of interest.\n* Use highlight with your mouse the time period you want to zoom into or use the pull downs at the top right to select specific time periods.\n* Note that by default the dates and time displayed are in your browser’s time zone, not the source cluster.   You can get it to display in UTC via the settings under the little gear symbol at the top of the page.\n* You can hide rows using the green slide-out tab to the left of each chart.\n* If there is a legend displayed you can click on elements within it to hide or display items, etc.\n* Click on the title of the chart and then the horizontal bars icon at the left to show/hide the legend and get a CSV export of the data.\n* There is no significance in whether things are displayed as lines, bars or points - we have used whatever seems to be clearest for the data.\n"
   },
   "content": "* Use the pull down at the very top left of the page (next to the spiral icon) to select which dashboard you want to look at.\n* Use the cluster and other pull downs to select the cluster and protocol of interest.\n* Use highlight with your mouse the time period you want to zoom into or use the pull downs at the top right to select specific time periods.\n* Note that by default the dates and time displayed are in your browser’s time zone, not the source cluster.   You can get it to display in UTC via the settings under the little gear symbol at the top of the page.\n* You can hide rows using the green slide-out tab to the left of each chart.\n* If there is a legend displayed you can click on elements within it to hide or display items, etc.\n* Click on the title of the chart and then the horizontal bars icon at the left to show/hide the legend and get a CSV export of the data.\n* There is no significance in whether things are displayed as lines, bars or points - we have used whatever seems to be clearest for the data.\n"
  },
  {
   "title": "$cluster",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://$cluster:8080/\">WebUI  for $cluster</a><br>\n<a href=/dashboard/db/isilon-data-insights-cluster-summary>Cluster list</a>\n"
   },
   "content": "<a target=\"_blank\" href=\"https://$cluster:8080/\">WebUI  for $cluster</a><br>\n<a href=/dashboard/db/isilon-data-insights-cluster-summary>Cluster list</a>\n"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_node_count_all{hostname=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_node_count_down{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_health{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1.0 - avg(isilon_cluster_cpu_idle_avg{hostname=~\"$cluster\"})/1000"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg(isilon_ifs_percent_avail{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "NFSv3 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs3_total_in_rate{hostname=~\"$cluster\"}+isilon_cluster_protostats_nfs3_total_out_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv3 Op/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs3_total_op_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv3 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs3_total_time_avg{hostname=~\"$cluster\"}/1000"
    }
   ]
  },
  {
   "title": "SMB2 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_in_rate{hostname=~\"$cluster\"}+isilon_cluster_protostats_smb2_total_out_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "SMB2 Op/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_op_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "SMB2 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_time_avg{hostname=~\"$cluster\"}/1000"
    }
   ]
  },
  {
   "title": "NFSv3 active clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(isilon_node_clientstats_active_nfs3{hostname=~\"$cluster\"})",
     "legendFormat": "nfs3 active clients"
    }
   ]
  },
  {
   "title": "NFSv4 active clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(isilon_node_clientstats_active_nfs4{hostname=~\"$cluster\"})",
     "legendFormat": "nfs4 active clients"
    }
   ]
  },
  {
   "title": "SMB1 active clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(isilon_node_clientstats_active_smb1{hostname=~\"$cluster\"})",
     "legendFormat": "smb1 active clients"
    }
   ]
  },
  {
   "title": "SMB2 active clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(isilon_node_clientstats_active_smb2{hostname=~\"$cluster\"})",
     "legendFormat": "smb2 active clients"
    }
   ]
  },
  {
   "title": "IFS ops",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_ifs_ops_in_rate{hostname=~\"$cluster\"}+isilon_ifs_ops_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "ifs ops"
    }
   ]
  },
  {
   "title": "NFSv4 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs4_total_in_rate{hostname=~\"$cluster\"}+isilon_cluster_protostats_nfs4_total_out_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv4 Op/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs4_total_op_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv4 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs4_total_time_avg{hostname=~\"$cluster\"}/1000"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent", "label": "Cluster Capacity Utilization" }
   ],
   "targets": [
    {
     "expr": "100.0 - isilon_ifs_percent_avail{hostname=~\"$cluster\"}",
     "legendFormat": "utilization"
    }
   ]
  },
  {
   "title": "Cluster Capacity Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Cluster Capacity Utilization" }
   ],
   "targets": [
    {
     "expr": "isilon_ifs_bytes_free{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_bytes_free"
    },
    {
     "expr": "isilon_ifs_bytes_avail{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_bytes_avail"
    },
    {
     "expr": "isilon_ifs_bytes_total{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_bytes_total"
    }
   ]
  },
  {
   "title": "Cluster SSD Capacity Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Cluster Capacity Utilization" }
   ],
   "targets": [
    {
     "expr": "isilon_ifs_ssd_bytes_free{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_ssd_bytes_free"
    },
    {
     "expr": "isilon_ifs_ssd_bytes_avail{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_ssd_bytes_avail"
    },
    {
     "expr": "isilon_ifs_ssd_bytes_total{hostname=~\"$cluster\"}",
     "legendFormat": "ifs_ssd_bytes_total"
    }
   ]
  },
  {
   "title": "Cluster CPU for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(isilon_cluster_cpu_intr_avg{hostname=~\"$cluster\"})/1000",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "avg(isilon_cluster_cpu_sys_avg{hostname=~\"$cluster\"})/1000",
     "legendFormat": "System"
    },
    {
     "expr": "avg(isilon_cluster_cpu_user_avg{hostname=~\"$cluster\"})/1000",
     "legendFormat": "User"
    },
    {
     "expr": "avg(isilon_cluster_cpu_idle_avg{hostname=~\"$cluster\"})/1000",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Cluster Protocol Operations for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops", "label": "Protocol Operations per Second" }
   ],
   "targets": [
    {
     "expr": "sum(isilon_cluster_protostats_http_op_rate{hostname=~\"$cluster\"})",
     "legendFormat": "http"
    },
    {
     "expr": "sum(isilon_cluster_protostats_nfs_op_rate{hostname=~\"$cluster\"})",
     "legendFormat": "nfs"
    },
    {
     "expr": "sum(isilon_cluster_protostats_nfs4_op_rate{hostname=~\"$cluster\"})",
     "legendFormat": "nfs4"
    },
    {
     "expr": "sum(isilon_cluster_protostats_smb2_op_rate{hostname=~\"$cluster\"})",
     "legendFormat": "smb2"
    }
   ]
  },
  {
   "title": "Active Client Connections by Protocol for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "isilon_node_clientstats_active_cifs{hostname=~\"$cluster\"}",
     "legendFormat": "cifs"
    },
    {
     "expr": "isilon_node_clientstats_active_nfs{hostname=~\"$cluster\"}",
     "legendFormat": "nfs"
    },
    {
     "expr": "isilon_node_clientstats_active_nfs4{hostname=~\"$cluster\"}",
     "legendFormat": "nfs4"
    },
    {
     "expr": "isilon_node_clientstats_active_http{hostname=~\"$cluster\"}",
     "legendFormat": "http"
    }
   ]
  },
  {
   "title": "Open Files for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "Open File Count" }
   ],
   "targets": [
    {
     "expr": "isilon_node_open_files{hostname=~\"$cluster\"}",
     "legendFormat": "open files"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_cluster_net_ext_bytes_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "bytes in"
    },
    {
     "expr": "isilon_cluster_net_ext_bytes_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "bytes out"
    }
   ]
  },
  {
   "title": "Cluster Network Packets and Errors for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Errors per Second" }
   ],
   "targets": [
    {
     "expr": "isilon_cluster_net_ext_errors_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "errors in"
    },
    {
     "expr": "isilon_cluster_net_ext_errors_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "errors out"
    },
    {
     "expr": "isilon_cluster_net_ext_packets_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "packets in"
    },
    {
     "expr": "isilon_cluster_net_ext_packets_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "packets out"
    }
   ]
  },
  {
   "title": "By Node Network Traffic for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_node_net_ext_bytes_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} bytes in"
    },
    {
     "expr": "isilon_node_net_ext_bytes_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} bytes out"
    }
   ]
  },
  {
   "title": "By Node Network Errors for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "isilon_node_net_ext_errors_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} errors in"
    },
    {
     "expr": "isilon_node_net_ext_errors_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} errors out"
    }
   ]
  },
  {
   "title": "By Node Internal Traffic for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_node_net_int_bytes_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} bytes in"
    },
    {
     "expr": "isilon_node_net_int_bytes_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "node{{node}} bytes out"
    }
   ]
  },
  {
   "title": "Cluster File System and Disk Throughput for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "Bps", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_ifs_bytes_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "ifs bytes in"
    },
    {
     "expr": "isilon_ifs_bytes_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "ifs bytes out"
    },
    {
     "expr": "isilon_cluster_disk_bytes_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "disk bytes in"
    },
    {
     "expr": "isilon_cluster_disk_bytes_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "disk bytes out"
    }
   ]
  },
  {
   "title": "Cluster Disk operations for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ops", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_cluster_disk_xfers_in_rate{hostname=~\"$cluster\"}+isilon_cluster_disk_xfers_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "disk total"
    },
    {
     "expr": "isilon_cluster_disk_xfers_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "disk xfers in"
    },
    {
     "expr": "isilon_cluster_disk_xfers_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "disk xfers out"
    }
   ]
  },
  {
   "title": "Cluster Disk Latency for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "none", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_node_disk_access_latency_avg{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} avg latency"
    },
    {
     "expr": "isilon_node_disk_access_slow_avg{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} disk slow"
    }
   ]
  },
  {
   "title": "Node Disk Busy for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "none", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_node_disk_busy_avg{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Node Disk Byte Rate for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
   "yaxes": [
    { "format": "none", "label": "Throughput" }
   ],
   "targets": [
    {
     "expr": "isilon_node_disk_bytes_in_rate_avg{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} in"
    },
    {
     "expr": "isilon_node_disk_bytes_out_rate_avg{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} out"
    }
   ]
  },
  {
   "title": "Job Engine Activity for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    {
     "format": "ops",
     "label": "Job Engine Operations per Second Count"
    }
   ],
   "targets": [
    {
     "expr": "isilon_cluster_protostats_jobd_total{hostname=~\"$cluster\"}",
     "legendFormat": "jobd"
    }
   ]
  },
  {
   "title": "OneFS File System Events for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isilon_node_ifs_heat_blocked_total{hostname=~\"$cluster\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "isilon_node_ifs_heat_contended_total{hostname=~\"$cluster\"}",
     "legendFormat": "contended"
    },
    {
     "expr": "isilon_node_ifs_heat_deadlocked_total{hostname=~\"$cluster\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "isilon_node_ifs_heat_getattr_total{hostname=~\"$cluster\"}",
     "legendFormat": "getattr"
    },
    {
     "expr": "isilon_node_ifs_heat_link_total{hostname=~\"$cluster\"}",
     "legendFormat": "linktotal"
    },
    {
     "expr": "isilon_node_ifs_heat_lock_total{hostname=~\"$cluster\"}",
     "legendFormat": "lock"
    },
    {
     "expr": "isilon_node_ifs_heat_lookup_total{hostname=~\"$cluster\"}",
     "legendFormat": "lookup"
    },
    {
     "expr": "isilon_node_ifs_heat_read_total{hostname=~\"$cluster\"}",
     "legendFormat": "read"
    },
    {
     "expr": "isilon_node_ifs_heat_rename_total{hostname=~\"$cluster\"}",
     "legendFormat": "rename"
    },
    {
     "expr": "isilon_node_ifs_heat_setattr_total{hostname=~\"$cluster\"}",
     "legendFormat": "setattr"
    },
    {
     "expr": "isilon_node_ifs_heat_unlink_total{hostname=~\"$cluster\"}",
     "legendFormat": "unlink"
    },
    {
     "expr": "isilon_node_ifs_heat_write_total{hostname=~\"$cluster\"}",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Cluster Cache Stats for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(isilon_node_ifs_cache_l1_data_prefetch_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l1_data_prefetch_start{hostname=~\"$cluster\"})",
     "legendFormat": "L1 Data Prefetch Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l1_meta_prefetch_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l1_meta_prefetch_start{hostname=~\"$cluster\"})",
     "legendFormat": "L1 Meta-Data Prefetch Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l1_data_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l1_data_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L1 Data Read Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l1_meta_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l1_meta_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L1 Meta-Data Read Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l2_data_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l2_data_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L2 Data Read Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l2_meta_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l2_meta_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L2 Meta-Data Read Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l3_data_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l3_data_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L3 Data Read Hit Ratio"
    },
    {
     "expr": "avg(isilon_node_ifs_cache_l3_meta_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l3_meta_read_start{hostname=~\"$cluster\"})",
     "legendFormat": "L3 Meta-Data Read Hit Ratio"
    }
   ]
  },
  {
   "title": "Node L3 Cache Stats for $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "isilon_node_ifs_cache_l3_data_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l3_data_read_start{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} L3 Data Prefetch Hit Ratio"
    },
    {
     "expr": "isilon_node_ifs_cache_l3_meta_read_hit{hostname=~\"$cluster\"} / isilon_node_ifs_cache_l3_meta_read_start{hostname=~\"$cluster\"}",
     "legendFormat": "node {{node}} L3 Meta-Data Prefetch Hit Ratio"
    }
   ]
  }
 ]
}