{
 "title": "Isilon Data Insights Cluster Concurrency",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({job=\"isilon\"},hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome to the Isilon Detail Dashboard for $cluster",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "* Use the pull down at the very top left of the page (next to the spiral icon) to select which dashboard you want to look at.\n* Use the cluster and other pull downs to select the cluster and protocol of interest.\n* Use highlight with your mouse the time period you want to zoom into or use the pull downs at the top right to select specific time periods.\n* Note that by default the dates and time displayed are in your browser’s time zone, not the source cluster.   You can get it to display in UTC via the settings under the little gear symbol at the top of the page.\n* You can hide rows using the green slide-out tab to the left of each chart.\n* If there is a legend displayed you can click on elements within it to hide or display items, etc.\n* Click on the title of the chart and then the horizontal bars icon at the left to show/hide the legend and get a CSV export of the data.\n* There is no significance in whether things are displayed as lines, bars or points - we have used whatever seems to be clearest for the data.\n"
   },
   "content": "* Use the pull down at the very top left of the page (next to the spiral icon) to select which dashboard you want to look at.\n* Use the cluster and other pull downs to select the cluster and protocol of interest.\n* Use highlight with your mouse the time period you want to zoom into or use the pull downs at the top right to select specific time periods.\n* Note that by default the dates and time displayed are in your browser’s time zone, not the source cluster.   You can get it to display in UTC via the settings under the little gear symbol at the top of the page.\n* You can hide rows using the green slide-out tab to the left of each chart.\n* If there is a legend displayed you can click on elements within it to hide or display items, etc.\n* Click on the title of the chart and then the horizontal bars icon at the left to show/hide the legend and get a CSV export of the data.\n* There is no significance in whether things are displayed as lines, bars or points - we have used whatever seems to be clearest for the data.\n"
  },
  {
   "title": "$cluster",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://$cluster:8080/\">WebUI  for $cluster</a><br>\n<a href=/dashboard/db/isilon-data-insights-cluster-summary>Cluster list</a>\n"
   },
   "content": "<a target=\"_blank\" href=\"https://$cluster:8080/\">WebUI  for $cluster</a><br>\n<a href=/dashboard/db/isilon-data-insights-cluster-summary>Cluster list</a>\n"
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_node_count_all{hostname=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_node_count_down{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Alert Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(isilon_cluster_health{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1.0 - avg(isilon_cluster_cpu_idle_avg{hostname=~\"$cluster\"})/1000"
    }
   ]
  },
  {
   "title": "Cluster Capacity Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg(isilon_ifs_percent_avail{hostname=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "NFSv3 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs_in_rate{hostname=~\"$cluster\"}+isilon_cluster_protostats_nfs_out_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv3 Op/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs_total_op_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "NFSv3 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_nfs_total_time_avg{hostname=~\"$cluster\"}/1000"
    }
   ]
  },
  {
   "title": "SMB2 Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 7 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_in_rate{hostname=~\"$cluster\"}+isilon_cluster_protostats_smb2_total_out_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "SMB2 Op/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 7 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_op_rate{hostname=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "SMB2 Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "isilon_cluster_protostats_smb2_total_time_avg{hostname=~\"$cluster\"}/1000"
    }
   ]
  },
  {
   "title": "Cluster IFS Concurrency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isilon_ifs_concurrency{hostname=~\"$cluster\"}",
     "legendFormat": "IFS Concurrency"
    },
    {
     "expr": "delta(isilon_cluster_disk_iosched_latency_avg{hostname=~\"$cluster\"}[2m])",
     "legendFormat": "Cluster Average Disk Latency Percent Change"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isilon_cluster_disk_iosched_latency_avg{hostname=~\"$cluster\"}",
     "legendFormat": "Cluster Average Disk Latency"
    },
    {
     "expr": "isilon_node_disk_iosched_latency_avg{hostname=~\"$cluster\"}",
     "legendFormat": "Node {{node}} Average Disk Latency"
    }
   ]
  },
  {
   "title": "Cluster Average Disk Latency Percent Change",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(isilon_node_disk_iosched_latency_avg{hostname=~\"$cluster\"}[2m])"
    }
   ]
  },
  {
   "title": "IFS OP Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isilon_ifs_ops_in_rate{hostname=~\"$cluster\"}",
     "legendFormat": "Cluster IFS Input OPs Count"
    },
    {
     "expr": "isilon_ifs_ops_out_rate{hostname=~\"$cluster\"}",
     "legendFormat": "Cluster IFS Output OPs Count"
    }
   ]
  }
 ]
}